name: 01_SDS_DART Update

on:
  schedule:
    - cron: '30 0 31 3 *'        # 3월 31일 오전 11시(UTC 0시)
    - cron: '30 0 17 5,8,11 *'   # 5월, 8월, 11월 17일 오전 11시(UTC 0시)
  workflow_dispatch:             # 수동 실행 가능

jobs:
  update-dart-reports:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      DART_API_KEY: ${{ secrets.DART_API_KEY }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      SDS_SPREADSHEET_ID: ${{ secrets.SDS_SPREADSHEET_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Verify environment variables
        run: |
          echo "Checking environment variables..."
          for var in "DART_API_KEY" "GOOGLE_CREDENTIALS" "SDS_SPREADSHEET_ID" "TELEGRAM_BOT_TOKEN" "TELEGRAM_CHANNEL_ID"; do
            if [ -z "${!var}" ]; then
              echo "Error: $var is not set"
              exit 1
            else
              echo "$var exists: true"
            fi
          done
          
      - name: Run DART update script
        id: update-dart
        run: python 018260_dart_update.py
        continue-on-error: true
